### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
The promised initial fastlane structure. I left out the screenshots as you already have them in your repo. So here are the suggested next steps:

* move over the screenshots from `screenshots/` to `fastlane/metadata/android/en-US/images/phoneScreenshots` (directory needs to be created first). Ideally, have no spaces in the file names. Keep the numbering at the start of the file names, the order of screenshots will then be kept as well.
* take a look at `fastlane/metadata/android/full_description.txt` and adjust as needed. Find some [formatting hints here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). I recommend what my notes there call "simple Markdown", as that works well for most places
* you can place your per-release changelogs into `fastlane/metadata/android/en-US/changelogs`. Naming convention of the files: `<versionCode>.txt` (so the current one would be `7.txt`), size limit: 500 chars
* ideally you'll have a dedicated icon available soon (that Android default one does not really fit). Hope you find someone to design it for you! That would then go to `fastlane/metadata/android/en-US/images/icon.png`
* if you have a featureGraphic (512x250 or 1024x500), that would go next to the icon. Icing on the cake, though :smile:
* additional languages might be provided by contributors later

Also important: Whatever is missing in another language will fall back to `en-US`. So e.g. no need to duplicate icon, featureGraphic or screenshots when you add a new language.

[More hints here](https://gitlab.com/-/snippets/1895688) – and if you have questions, be welcome to ask :smiley:

### CODE REVIEW

**Comment by jpkhawam** [comment]
Thank you! This is greatly appreciated and clear 👍🏼. I'll get to them asap, and totally on the app icon, I just have 0 design skills and don't want something generic. I'll ask if someone can make it happen.
Thanks again!

**Comment by IzzySoft** [comment]
Pointer: Currently your screenshots will get mixed like 1-10-11-12-2-3…

image

Pad the initial numbering, like `01-` instead of `1-` if you want that fixed :wink:

I've now enabled what is there currently. Should you add new element **types** (icon, featureGraphic, `video.txt`) please give me a ping so I check them as well. No need to ping me if you e.g. add more screenshots, or other languages – those will be picked up automatically.

**Comment by jpkhawam** [comment]
fixed! thank you!
I really appreciate the guidance, I am aware most people don't get that so I am grateful for the time you're taking

> Should you add new element types (icon, featureGraphic, video.txt) please give me a ping so I check them as well.

Noted!

**Comment by IzzySoft** [comment]
I try my very best. You pick it up so fast that you always encourage me to place the next hint – but at the moment I'm running out of hints :rofl: Thanks!

**Comment by jpkhawam** [comment]
Hello, @IzzySoft! Sorry for the ping, I just want to ask if I need to do something specific to get new releases to get to your repo, and if not, how long does it usually take?

**Comment by IzzySoft** [comment]
Checking my config for your app:

```yaml
AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
```

keep tagging and attaching the APK :smiley:

Oops: Pre-Releases, my bad… give me a sec, toggling a bit… Done, now accepting pre-releases. Apologies for my missing that! Dong a test-run to compensate… Looks good now:

```
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/releases'
com.jpkhawam.nabu: checking tag 'v0.7.1'
com.jpkhawam.nabu: lastRelNo set to '0.7.1', checking for files
Upstream file date (2022-11-01 01:07) is newer than ours (2022-10-29 19:37).
com.jpkhawam.nabu: returning ['0.7.1','https://github.com/jpkhawam/Nabu/releases/download/v0.7.1/nabu-v0.7.1-alpha.apk']
com.jpkhawam.nabu: 0.7.0/0.7.1, https://github.com/jpkhawam/Nabu/releases: https://github.com/jpkhawam/Nabu/releases/download/v0.7.1/nabu-v0.7.1-alpha.apk
- Grabbing update for com.jpkhawam.nabu: OK
- Checking '/web/ftp/repo/fdroid/repo/com.jpkhawam.nabu_8.apk' for libraries and malware …
com.jpkhawam.nabu: check if repo contains FUNDING.yml
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/.github'
com.jpkhawam.nabu: Github reports "Not Found" for https://api.github.com/repos/jpkhawam/Nabu/contents/.github
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/'
com.jpkhawam.nabu: no FUNDING.yml detected.
com.jpkhawam.nabu: checking Fastlane for per-release changelogs
com.jpkhawam.nabu: fetched 'https://github.com/jpkhawam/Nabu/raw/main/fastlane/metadata/android/en-US/changelogs/8.txt'
com.jpkhawam.nabu: calling 'getFastlaneMeta(github,[host:github.com,owner:jpkhawam,repo:Nabu,path:/fastlane/metadata/android])'
com.jpkhawam.nabu: FastlaneFeatures shortdesc,fulldescMD,screenshotsJPG
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/fastlane%2Fmetadata%2Fandroid'
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fchangelogs'
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
com.jpkhawam.nabu: looking for 'https://api.github.com/repos/jpkhawam/Nabu/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
com.jpkhawam.nabu: checking locale 'en-US'
com.jpkhawam.nabu: replacing 'metadata/com.jpkhawam.nabu/en-US/full_description.txt' with fromMD
com.jpkhawam.nabu: updating 'metadata/com.jpkhawam.nabu/en-US/short_description.txt'
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/01-accessibility_prompt_light.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/02-accessibility_prompt_dark.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/03-main_screen_light.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/04-main_screen_dark.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/05-main_screen_light_dyslexia.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/06-main_screen_dark_dyslexia_larger_font.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/07-note_edit_light.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/08-note_edit_dark.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/09-note_edit_dark_dyslexia.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/10-note_edit_light_larger_font.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/11-extra_1.png' as JPG
com.jpkhawam.nabu: updating 'repo/com.jpkhawam.nabu/en-US/phoneScreenshots/12-extra_2.png' as JPG
com.jpkhawam.nabu: cross-checking for obsolete screenshots
com.jpkhawam.nabu: screenshots in Fastlane: 01-accessibility_prompt_light,02-accessibility_prompt_dark,03-main_screen_light,04-main_screen_dark,05-main_screen_light_dyslexia,06-main_screen_dark_dyslexia_larger_font,07-note_edit_light,08-note_edit_dark,09-note_edit_dark_dyslexia,10-note_edit_light_larger_font,11-extra_1,12-extra_2
com.jpkhawam.nabu: local screenshots checked: 01-accessibility_prompt_light,02-accessibility_prompt_dark,03-main_screen_light,04-main_screen_dark,05-main_screen_light_dyslexia,06-main_screen_dark_dyslexia_larger_font,07-note_edit_light,08-note_edit_dark,09-note_edit_dark_dyslexia,10-note_edit_light_larger_font,11-extra_1,12-extra_2
```

**Comment by jpkhawam** [comment]
Thanks for the quick fix! 😄 I'm marking them as pre-releases as I don't feel production ready release fits yet

**Pull request merged**
